export const GET_DATA_ACCEL_SENSOR = 'GET_DATA_ACCEL_SENSOR';
export const GET_DATA_GYROS_SENSOR = 'GET_DATA_GYROS_SENSOR';
export const SAVE_DATA_ACCEL_SENSOR = 'SAVE_DATA_ACCEL_SENSOR';
export const SAVE_DATA_GYROS_SENSOR = 'SAVE_DATA_GYROS_SENSOR';
export const SAVE_DATA_MAGNE_SENSOR = 'SAVE_DATA_MAGNE_SENSOR';
export const CALCULATE_SPEED_ACCEL = 'CALCULATE_SPEED_ACCEL';
export const SAVE_DATA_USER_LOGED = 'SAVE_DATA_USER_LOGED';
export const SAVE_COLLECTIONS = 'SAVE_COLLECTIONS';
